export const EXPLORE_CHANGE_FIELD = 'EXPLORE_CHANGE_FIELD';
export const EXPLORE_SUBMIT = 'EXPLORE_SUBMIT';

export const ENTITY_REPO_HAS_CHANGED = 'ENTITY_REPO_HAS_CHANGED';

export const LOADING_STARTED = 'LOADING_STARTED';
export const LOADING_FINISHED = 'LOADING_FINISHED';
export const LOADING_FAILED = 'LOADING_FAILED';

export const DISMISS_ERROR_MESSAGE = 'DISMISS_ERROR_MESSAGE';
export const RESET_PAGINATION_STATE = 'RESET_PAGINATION_STATE';

export const STARRED_FETCHED = 'STARRED_FETCHED';
export const STARRED_FETCH_MORE = 'STARRED_FETCH_MORE';

export const STARGAZERS_FETCHED = 'STARGAZERS_FETCHED';
export const STARGAZERS_FETCH_MORE = 'STARGAZERS_FETCH_MORE';
